# Prompts are defined inside agents.py
# as inline strings for clarity.
# This file holds any shared prompt utilities.

def format_report_as_markdown(
    report: dict,
    query: str
) -> str:
    """
    Convert final report dict to
    clean markdown string.
    Used for copy-to-clipboard feature.
    """
    md = f"# Research Report\n\n"
    md += f"**Query:** {query}\n\n"
    md += "---\n\n"

    md += "## Executive Summary\n\n"
    md += (
        report.get(
            "executive_summary", ""
        ) + "\n\n"
    )

    if report.get("key_findings"):
        md += "## Key Findings\n\n"
        for i, f in enumerate(
            report["key_findings"], 1
        ):
            md += (
                f"**{i}. "
                f"{f.model_dump().get('finding', '')}**\n\n"
            )
            md += (
                f"{f.model_dump().get('detail', '')}\n\n"
            )

    if report.get("section_breakdown"):
        md += "## Detailed Analysis\n\n"
        for section in report["section_breakdown"]:
            md += (
                f"### "
                f"{section.model_dump().get('section_title', '')}"
                f"\n\n"
            )
            md += (
                section.model_dump().get("content", "")
                + "\n\n"
            )

    if report.get("conclusions"):
        md += "## Conclusions\n\n"
        for c in report["conclusions"]:
            md += f"- {c}\n"
        md += "\n"

    if report.get("follow_up_questions"):
        md += "## Follow-up Questions\n\n"
        for q in report["follow_up_questions"]:
            md += f"- {q}\n"
        md += "\n"

    md += "---\n"
    md += (
        f"*Confidence Score: "
        f"{report.get('confidence_score', 5)}/10*\n"
    )
    md += (
        "*Generated by ResearchForge AI — "
        "Day 9 of 14*\n"
    )

    return md